### ISSUE TITLE
Why is a token required

### ISSUE THREAD

**Issue by goleary** [wonism/gatsby-source-notion-contents#1]
It would be nice if this plugin could be used to access public notion pages so I don't have to share the token from my cookie with it.

**Comment by wonism** [comment]
You can use this without token from v1.1.0

**Comment by goleary** [comment]
The documentation on the gatsby website has not been updated:
![image](https://user-images.githubusercontent.com/16123225/83332433-039e2280-a250-11ea-81f5-3772e84871f1.png)

**Comment by wonism** [comment]
I guess it had taken a little time.
Thanks anyway :)
